#!/bin/bash
#
# Copyright 2014-2016 Facundo Batista, Nicolás Demarchi

set -eu

if [ $# -ne 0 ]; then
    TARGET_TESTS="$@"
else
    TARGET_TESTS=""
fi

./bin/fades -r requirements.txt -x pytest $TARGET_TESTS
