#!/bin/bash
#
# Copyright 2014-2017 Facundo Batista, Nicolás Demarchi

set -eu

if [ $# -ne 0 ]; then
    TARGET_TESTS="$@"
else
    TARGET_TESTS="fades tests"
fi

FADES='./bin/fades -r requirements.txt'

$FADES -x nosetests --with-xcoverage --cover-package=fades -v -s $TARGET_TESTS
