name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - ${{ github.workspace }}:/fades
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm python3 
      - name: Simple fades run
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          cd /fades
          ls -l
          echo "Fades V"
          bin/fades --version
          echo "Fades R"
          bin/fades -v -d pytest -x pytesxt --version
