name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - ${{ github.workspace }}:/project
    steps:
      - name: Simple fades run
        run: |
          cd /project
          ls -l
          bin/fades -v -d pytest -x pytesxt --version
