name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - ${{ github.workspace }}:/project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Simple fades run
        run: |
          echo "minusc"
          echo ${{ github.workspace }}
          echo "MAYUsc"
          echo $GITHUB_WORKSPACE
          echo "cd and ls"
          cd /project
          ls -l
          echo "Fades"
          bin/fades -v -d pytest -x pytesxt --version
