name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15, windows-2019, windows-2016]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
            # https://stackoverflow.com/questions/62616464/what-versions-of-python-is-shipped-with-macos-11-big-sur 
            - os: macos-11
              python-version: 3.6
            - os: macos-11
              python-version: 3.7

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U -r requirements.txt
      - name: Run tests
        run: |
          pytest
